#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jan  6 16:13:58 2023

@author: nethrachekuri
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset=pd.read_csv(r"C:\Users\neth\Desktop\LR.csv")
x = dataset.iloc[:,[2,3]].values
y = dataset.iloc[:,-1].values

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

from sklearn.svm import SVC
classifier = SVC()
classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)

bias=classifier.score(x_train,y_train)
bias
variance= classifier.score(x_test,y_test)
variance

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

cm = confusion_matrix(y_test,y_pred)
cr = classification_report(y_test, y_pred)

from sklearn.metrics import accuracy_score
c = accuracy_score(y_test, y_pred)

from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier, x = x_train, y=y_train,cv=10)
print("Accuracy:{:2f}%".format(accuracies.mean()*100))
print("Standard Deviation:{:2f}%".format(accuracies.std()*100))